name: Publish Stitch for VSCode MacOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'bscotch-stitch-vscode@*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish-mac:
    runs-on: macos-latest
    steps:
      # SETUP
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # Remove any existing pnpm-lock.yaml files, which are
      # both platform-specific and will likely halt the build.
      - name: Remove pnpm-lock.yaml
        run: find $(pwd) -name pnpm-lock.yaml -delete

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      

      #- run: curl https://sh.rustup.rs -sSf | sh -s -- -y



      - run: corepack enable
      # BUILD DEPS
      - name: Build everything
        run: pnpm turbo run build --only --filter=bscotch-stitch-vscode... --filter=stitch-monorepo
      - run: pwd



      - name: Build VSCode
        run: |
          cd packages/vscode && \
          pnpm build

      - name: Install VSCE
        run: pnpm install @vscode/vsce

      - run: pwd
      - name: Create VSCodePackage
        run: ./node_modules/.bin/vsce package --no-dependencies --githubBranch develop --out bscotch-stitch-vscode-mac.vsix
        env:
          APPDATA: $HOME/.config
          PROGRAMDATA: /Users/Shared/
          PROGRAMFILES: $HOME/Applications

      # Publish created package as a github release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: bscotch-stitch-*.vsix

          body: |
            This is an auto-generated release for ${{ github.ref }}.
            It contains the latest version of the MacOS Stitch for VSCode extension.