name: Publish Stitch for VSCode MacOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'bscotch-stitch-vscode@*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish-mac:
    runs-on: macos-latest
    steps:
      # SETUP
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      # Remove any existing pnpm-lock.yaml files, which are
      # both platform-specific and will likely halt the build.
      - name: Remove pnpm-lock.yaml
        run: find $(pwd) -name pnpm-lock.yaml -delete

      #- run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: |
          corepack enable && \
          pnpm install --filter=bscotch-stitch-vscode... --filter=stitch-monorepo
      - run: pwd



      # BUILD DEPS
      - name: Build deps
        run: pnpm turbo run build --only --filter=bscotch-stitch-vscode...

      - name: Build VSCode
        run: |
          cd packages/vscode && \
          pnpm install . && \
          pnpm build && \
          pnpm install @vscode/vsce

      - name: Create VSCodePackage
        run: pnpm vsce package --no-dependencies --githubBranch develop --out bscotch-stitch-vscode-mac.vsix
        env:
          APPDATA: $HOME/.config
          PROGRAMDATA: /Users/Shared/
          PROGRAMFILES: $HOME/Applications

      # Publish created package as a github release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: bscotch-stitch-*.vsix

          body: |
            This is an auto-generated release for ${{ github.ref }}.
            It contains the latest version of the MacOS Stitch for VSCode extension.