name: Test Stitch for VSCode on MacOS

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: macos-latest
    steps:
      # SETUP
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      # Remove any existing pnpm-lock.yaml files, which are
      # both platform-specific and will likely halt the build.
      - run: rm -f $(pwd)/**/pnpm-lock.yaml

      - run: corepack enable
      - run: pnpm install --filter=bscotch-stitch-vscode... --filter=stitch-monorepo
      - run: pwd

      # BUILD DEPS
      - name: Build
        run: pnpm turbo run build --only --filter=bscotch-stitch-vscode...

      # TEST
      - name: Test
        continue-on-error: true
        run: pnpm turbo run test --only --filter=bscotch-stitch-vscode...


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test-results-mac            # Name of the check run which will be created
          path: ''   # Path to test results
          reporter: mocha-json        # Format of test results